apiVersion: v1
kind: Service
metadata:
  name: ngx-instance-0
  namespace: default
  labels:
    name: ngx-instance-0
  annotations:
    # NOTE: the following annotation is a beta feature and
    # only available in GCE/GKE and Azure as of now
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  selector:
    app: ngx-instance-0-dep
  ports:
  - port: 27017
    targetPort: 27017
    name: ngx-public-mdb-port
    protocol: TCP
  - port: 80
    targetPort: 80
    name: ngx-bdb-api-port
    protocol: TCP
  - port: 81
    targetPort: 81
    name: ngx-bdb-ws-port
    protocol: TCP
  type: LoadBalancer
